### ISSUE TITLE
Repo Inquiry

### ISSUE THREAD

**Issue by J-Cook-jr** [Fantom-foundation/Artion-Client#267]
Is this Repo still active? After forking and cloning "Artion-Client", I run "npm install" and I get a lot of warnings about the deprecated dependencies. Then I move forward and run "npm start", and I get errors about the outdated dependencies. The outdated dependencies would not allow me to move forward with viewing the project in my browser. So, am I supposed to just use the "Artion-Client V-2" instead?

**Comment by YassinElf** [comment]
Bumping this
