### ISSUE TITLE
Testnet Endpoint API down ?

### ISSUE THREAD

**Issue by jack75015** [Fantom-foundation/Artion-Client#299]
Hi

I recently pulled the project, and setup it to work on the testnet.
But every call to the testnet api failed..
`https://api.testnet.artion.io`

Any ideas?
Thanks :)

**Comment by quan8** [comment]
@jack75015  it's not supported.

**Comment by jack75015** [comment]
Hey @quan8 , thanks for your response.

So why is it in the code so? :)
It work like with your are not setting the MAINNET option in your .env, it will call the testnet api 

Also, do you know a way to build Artion locally, working with fantom testnet? :)

Thanks
